apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "job-manager-server.fullname" . }}-http
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /v1/fine_tuning
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
      - path: /v1/workspaces
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
      - path: /v1/batch
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}
      - path: /v1/jobs
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-http
            port:
              number: {{ .Values.httpPort }}

{{- if .Values.global.workerServiceIngress.create }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "job-manager-server.fullname" . }}-worker-service-grpc
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.workerServiceIngress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /llmariner.jobs.server.v1.JobWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
      - path: /llmariner.fine_tuning.server.v1.FineTuningWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
      - path: /llmariner.workspace.server.v1.WorkspaceWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
      - path: /llmariner.batch.server.v1.BatchWorkerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-worker-service-grpc
            port:
              number: {{ .Values.workerServiceGrpcPort }}
{{- end -}}

{{- if .Values.syncerServiceIngress.create }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "job-manager-server.fullname" . }}-syncer-service-grpc
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.syncerServiceIngress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  {{- with .Values.global.ingress.tls }}
  tls:
  - hosts:
      {{- toYaml .hosts | nindent 6 }}
    {{- if .secretName }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - path:  /llmariner.syncer.server.v1.SyncerService
        pathType: Prefix
        backend:
          service:
            name: {{ include "job-manager-server.fullname" . }}-syncer-service-grpc
            port:
              number: {{ .Values.syncerServiceGrpcPort }}
{{- end -}}
