// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BatchServiceClient is the client API for BatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BatchServiceClient interface {
	CreateBatchJob(ctx context.Context, in *CreateBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error)
	ListBatchJobs(ctx context.Context, in *ListBatchJobsRequest, opts ...grpc.CallOption) (*ListBatchJobsResponse, error)
	GetBatchJob(ctx context.Context, in *GetBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error)
	CancelBatchJob(ctx context.Context, in *CancelBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error)
	DeleteBatchJob(ctx context.Context, in *DeleteBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error)
}

type batchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchServiceClient(cc grpc.ClientConnInterface) BatchServiceClient {
	return &batchServiceClient{cc}
}

func (c *batchServiceClient) CreateBatchJob(ctx context.Context, in *CreateBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error) {
	out := new(BatchJob)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchService/CreateBatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) ListBatchJobs(ctx context.Context, in *ListBatchJobsRequest, opts ...grpc.CallOption) (*ListBatchJobsResponse, error) {
	out := new(ListBatchJobsResponse)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchService/ListBatchJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) GetBatchJob(ctx context.Context, in *GetBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error) {
	out := new(BatchJob)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchService/GetBatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) CancelBatchJob(ctx context.Context, in *CancelBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error) {
	out := new(BatchJob)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchService/CancelBatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchServiceClient) DeleteBatchJob(ctx context.Context, in *DeleteBatchJobRequest, opts ...grpc.CallOption) (*BatchJob, error) {
	out := new(BatchJob)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchService/DeleteBatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchServiceServer is the server API for BatchService service.
// All implementations must embed UnimplementedBatchServiceServer
// for forward compatibility
type BatchServiceServer interface {
	CreateBatchJob(context.Context, *CreateBatchJobRequest) (*BatchJob, error)
	ListBatchJobs(context.Context, *ListBatchJobsRequest) (*ListBatchJobsResponse, error)
	GetBatchJob(context.Context, *GetBatchJobRequest) (*BatchJob, error)
	CancelBatchJob(context.Context, *CancelBatchJobRequest) (*BatchJob, error)
	DeleteBatchJob(context.Context, *DeleteBatchJobRequest) (*BatchJob, error)
	mustEmbedUnimplementedBatchServiceServer()
}

// UnimplementedBatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBatchServiceServer struct {
}

func (UnimplementedBatchServiceServer) CreateBatchJob(context.Context, *CreateBatchJobRequest) (*BatchJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBatchJob not implemented")
}
func (UnimplementedBatchServiceServer) ListBatchJobs(context.Context, *ListBatchJobsRequest) (*ListBatchJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBatchJobs not implemented")
}
func (UnimplementedBatchServiceServer) GetBatchJob(context.Context, *GetBatchJobRequest) (*BatchJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchJob not implemented")
}
func (UnimplementedBatchServiceServer) CancelBatchJob(context.Context, *CancelBatchJobRequest) (*BatchJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBatchJob not implemented")
}
func (UnimplementedBatchServiceServer) DeleteBatchJob(context.Context, *DeleteBatchJobRequest) (*BatchJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBatchJob not implemented")
}
func (UnimplementedBatchServiceServer) mustEmbedUnimplementedBatchServiceServer() {}

// UnsafeBatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchServiceServer will
// result in compilation errors.
type UnsafeBatchServiceServer interface {
	mustEmbedUnimplementedBatchServiceServer()
}

func RegisterBatchServiceServer(s grpc.ServiceRegistrar, srv BatchServiceServer) {
	s.RegisterService(&BatchService_ServiceDesc, srv)
}

func _BatchService_CreateBatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).CreateBatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchService/CreateBatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).CreateBatchJob(ctx, req.(*CreateBatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_ListBatchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBatchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).ListBatchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchService/ListBatchJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).ListBatchJobs(ctx, req.(*ListBatchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_GetBatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).GetBatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchService/GetBatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).GetBatchJob(ctx, req.(*GetBatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_CancelBatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).CancelBatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchService/CancelBatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).CancelBatchJob(ctx, req.(*CancelBatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchService_DeleteBatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchServiceServer).DeleteBatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchService/DeleteBatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchServiceServer).DeleteBatchJob(ctx, req.(*DeleteBatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchService_ServiceDesc is the grpc.ServiceDesc for BatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.batch.server.v1.BatchService",
	HandlerType: (*BatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBatchJob",
			Handler:    _BatchService_CreateBatchJob_Handler,
		},
		{
			MethodName: "ListBatchJobs",
			Handler:    _BatchService_ListBatchJobs_Handler,
		},
		{
			MethodName: "GetBatchJob",
			Handler:    _BatchService_GetBatchJob_Handler,
		},
		{
			MethodName: "CancelBatchJob",
			Handler:    _BatchService_CancelBatchJob_Handler,
		},
		{
			MethodName: "DeleteBatchJob",
			Handler:    _BatchService_DeleteBatchJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/batch_service.proto",
}

// BatchWorkerServiceClient is the client API for BatchWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BatchWorkerServiceClient interface {
	ListQueuedInternalBatchJobs(ctx context.Context, in *ListQueuedInternalBatchJobsRequest, opts ...grpc.CallOption) (*ListQueuedInternalBatchJobsResponse, error)
	GetInternalBatchJob(ctx context.Context, in *GetInternalBatchJobRequest, opts ...grpc.CallOption) (*InternalBatchJob, error)
	UpdateBatchJobState(ctx context.Context, in *UpdateBatchJobStateRequest, opts ...grpc.CallOption) (*UpdateBatchJobStateResponse, error)
}

type batchWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchWorkerServiceClient(cc grpc.ClientConnInterface) BatchWorkerServiceClient {
	return &batchWorkerServiceClient{cc}
}

func (c *batchWorkerServiceClient) ListQueuedInternalBatchJobs(ctx context.Context, in *ListQueuedInternalBatchJobsRequest, opts ...grpc.CallOption) (*ListQueuedInternalBatchJobsResponse, error) {
	out := new(ListQueuedInternalBatchJobsResponse)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchWorkerService/ListQueuedInternalBatchJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchWorkerServiceClient) GetInternalBatchJob(ctx context.Context, in *GetInternalBatchJobRequest, opts ...grpc.CallOption) (*InternalBatchJob, error) {
	out := new(InternalBatchJob)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchWorkerService/GetInternalBatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchWorkerServiceClient) UpdateBatchJobState(ctx context.Context, in *UpdateBatchJobStateRequest, opts ...grpc.CallOption) (*UpdateBatchJobStateResponse, error) {
	out := new(UpdateBatchJobStateResponse)
	err := c.cc.Invoke(ctx, "/llmariner.batch.server.v1.BatchWorkerService/UpdateBatchJobState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchWorkerServiceServer is the server API for BatchWorkerService service.
// All implementations must embed UnimplementedBatchWorkerServiceServer
// for forward compatibility
type BatchWorkerServiceServer interface {
	ListQueuedInternalBatchJobs(context.Context, *ListQueuedInternalBatchJobsRequest) (*ListQueuedInternalBatchJobsResponse, error)
	GetInternalBatchJob(context.Context, *GetInternalBatchJobRequest) (*InternalBatchJob, error)
	UpdateBatchJobState(context.Context, *UpdateBatchJobStateRequest) (*UpdateBatchJobStateResponse, error)
	mustEmbedUnimplementedBatchWorkerServiceServer()
}

// UnimplementedBatchWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBatchWorkerServiceServer struct {
}

func (UnimplementedBatchWorkerServiceServer) ListQueuedInternalBatchJobs(context.Context, *ListQueuedInternalBatchJobsRequest) (*ListQueuedInternalBatchJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueuedInternalBatchJobs not implemented")
}
func (UnimplementedBatchWorkerServiceServer) GetInternalBatchJob(context.Context, *GetInternalBatchJobRequest) (*InternalBatchJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInternalBatchJob not implemented")
}
func (UnimplementedBatchWorkerServiceServer) UpdateBatchJobState(context.Context, *UpdateBatchJobStateRequest) (*UpdateBatchJobStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBatchJobState not implemented")
}
func (UnimplementedBatchWorkerServiceServer) mustEmbedUnimplementedBatchWorkerServiceServer() {}

// UnsafeBatchWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchWorkerServiceServer will
// result in compilation errors.
type UnsafeBatchWorkerServiceServer interface {
	mustEmbedUnimplementedBatchWorkerServiceServer()
}

func RegisterBatchWorkerServiceServer(s grpc.ServiceRegistrar, srv BatchWorkerServiceServer) {
	s.RegisterService(&BatchWorkerService_ServiceDesc, srv)
}

func _BatchWorkerService_ListQueuedInternalBatchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuedInternalBatchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchWorkerServiceServer).ListQueuedInternalBatchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchWorkerService/ListQueuedInternalBatchJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchWorkerServiceServer).ListQueuedInternalBatchJobs(ctx, req.(*ListQueuedInternalBatchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchWorkerService_GetInternalBatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInternalBatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchWorkerServiceServer).GetInternalBatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchWorkerService/GetInternalBatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchWorkerServiceServer).GetInternalBatchJob(ctx, req.(*GetInternalBatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchWorkerService_UpdateBatchJobState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBatchJobStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchWorkerServiceServer).UpdateBatchJobState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.batch.server.v1.BatchWorkerService/UpdateBatchJobState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchWorkerServiceServer).UpdateBatchJobState(ctx, req.(*UpdateBatchJobStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchWorkerService_ServiceDesc is the grpc.ServiceDesc for BatchWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.batch.server.v1.BatchWorkerService",
	HandlerType: (*BatchWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListQueuedInternalBatchJobs",
			Handler:    _BatchWorkerService_ListQueuedInternalBatchJobs_Handler,
		},
		{
			MethodName: "GetInternalBatchJob",
			Handler:    _BatchWorkerService_GetInternalBatchJob_Handler,
		},
		{
			MethodName: "UpdateBatchJobState",
			Handler:    _BatchWorkerService_UpdateBatchJobState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/batch_service.proto",
}
