// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: api/v1/syncer_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatchKubernetesObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string                                  `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // empty namespace means cluster-scope resource.
	Group     string                                  `protobuf:"bytes,3,opt,name=Group,proto3" json:"Group,omitempty"`
	Version   string                                  `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	Resource  string                                  `protobuf:"bytes,5,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Resources *PatchKubernetesObjectRequest_Resources `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	// JSON encoded object data.
	Data []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PatchKubernetesObjectRequest) Reset() {
	*x = PatchKubernetesObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchKubernetesObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchKubernetesObjectRequest) ProtoMessage() {}

func (x *PatchKubernetesObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchKubernetesObjectRequest.ProtoReflect.Descriptor instead.
func (*PatchKubernetesObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{0}
}

func (x *PatchKubernetesObjectRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PatchKubernetesObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchKubernetesObjectRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PatchKubernetesObjectRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PatchKubernetesObjectRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PatchKubernetesObjectRequest) GetResources() *PatchKubernetesObjectRequest_Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PatchKubernetesObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PatchKubernetesObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Uid       string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *PatchKubernetesObjectResponse) Reset() {
	*x = PatchKubernetesObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchKubernetesObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchKubernetesObjectResponse) ProtoMessage() {}

func (x *PatchKubernetesObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchKubernetesObjectResponse.ProtoReflect.Descriptor instead.
func (*PatchKubernetesObjectResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{1}
}

func (x *PatchKubernetesObjectResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *PatchKubernetesObjectResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type DeleteKubernetesObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Group     string `protobuf:"bytes,4,opt,name=Group,proto3" json:"Group,omitempty"`
	Version   string `protobuf:"bytes,5,opt,name=Version,proto3" json:"Version,omitempty"`
	Resource  string `protobuf:"bytes,6,opt,name=Resource,proto3" json:"Resource,omitempty"`
}

func (x *DeleteKubernetesObjectRequest) Reset() {
	*x = DeleteKubernetesObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKubernetesObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKubernetesObjectRequest) ProtoMessage() {}

func (x *DeleteKubernetesObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKubernetesObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteKubernetesObjectRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteKubernetesObjectRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DeleteKubernetesObjectRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteKubernetesObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteKubernetesObjectRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DeleteKubernetesObjectRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeleteKubernetesObjectRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type DeleteKubernetesObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKubernetesObjectResponse) Reset() {
	*x = DeleteKubernetesObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKubernetesObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKubernetesObjectResponse) ProtoMessage() {}

func (x *DeleteKubernetesObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKubernetesObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteKubernetesObjectResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{3}
}

type ListClusterIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListClusterIDsRequest) Reset() {
	*x = ListClusterIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterIDsRequest) ProtoMessage() {}

func (x *ListClusterIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterIDsRequest.ProtoReflect.Descriptor instead.
func (*ListClusterIDsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{4}
}

type ListClusterIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListClusterIDsResponse) Reset() {
	*x = ListClusterIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListClusterIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClusterIDsResponse) ProtoMessage() {}

func (x *ListClusterIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClusterIDsResponse.ProtoReflect.Descriptor instead.
func (*ListClusterIDsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListClusterIDsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PatchKubernetesObjectRequest_Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GpuLimit int32 `protobuf:"varint,1,opt,name=gpu_limit,json=gpuLimit,proto3" json:"gpu_limit,omitempty"`
}

func (x *PatchKubernetesObjectRequest_Resources) Reset() {
	*x = PatchKubernetesObjectRequest_Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_syncer_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchKubernetesObjectRequest_Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchKubernetesObjectRequest_Resources) ProtoMessage() {}

func (x *PatchKubernetesObjectRequest_Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_syncer_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchKubernetesObjectRequest_Resources.ProtoReflect.Descriptor instead.
func (*PatchKubernetesObjectRequest_Resources) Descriptor() ([]byte, []int) {
	return file_api_v1_syncer_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PatchKubernetesObjectRequest_Resources) GetGpuLimit() int32 {
	if x != nil {
		return x.GpuLimit
	}
	return 0
}

var File_api_v1_syncer_service_proto protoreflect.FileDescriptor

var file_api_v1_syncer_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6c,
	0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0xbc, 0x02, 0x0a, 0x1c, 0x50, 0x61,
	0x74, 0x63, 0x68, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x42, 0x2e, 0x6c, 0x6c,
	0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x28,
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x70, 0x75, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x67, 0x70, 0x75, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x50, 0x0a, 0x1d, 0x50, 0x61, 0x74, 0x63,
	0x68, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x1d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x32, 0xaf, 0x03, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x8e, 0x01, 0x0a, 0x15, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x38, 0x2e, 0x6c,
	0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b,
	0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x39, 0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e,
	0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65,
	0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x91, 0x01, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x39,
	0x2e, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65,
	0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x6c, 0x6c, 0x6d, 0x61,
	0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x75, 0x62,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x73, 0x12, 0x31, 0x2e, 0x6c, 0x6c, 0x6d, 0x61,
	0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6c,
	0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x6c, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x72, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_syncer_service_proto_rawDescOnce sync.Once
	file_api_v1_syncer_service_proto_rawDescData = file_api_v1_syncer_service_proto_rawDesc
)

func file_api_v1_syncer_service_proto_rawDescGZIP() []byte {
	file_api_v1_syncer_service_proto_rawDescOnce.Do(func() {
		file_api_v1_syncer_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_syncer_service_proto_rawDescData)
	})
	return file_api_v1_syncer_service_proto_rawDescData
}

var file_api_v1_syncer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_syncer_service_proto_goTypes = []interface{}{
	(*PatchKubernetesObjectRequest)(nil),           // 0: llmariner.syncer.server.v1.PatchKubernetesObjectRequest
	(*PatchKubernetesObjectResponse)(nil),          // 1: llmariner.syncer.server.v1.PatchKubernetesObjectResponse
	(*DeleteKubernetesObjectRequest)(nil),          // 2: llmariner.syncer.server.v1.DeleteKubernetesObjectRequest
	(*DeleteKubernetesObjectResponse)(nil),         // 3: llmariner.syncer.server.v1.DeleteKubernetesObjectResponse
	(*ListClusterIDsRequest)(nil),                  // 4: llmariner.syncer.server.v1.ListClusterIDsRequest
	(*ListClusterIDsResponse)(nil),                 // 5: llmariner.syncer.server.v1.ListClusterIDsResponse
	(*PatchKubernetesObjectRequest_Resources)(nil), // 6: llmariner.syncer.server.v1.PatchKubernetesObjectRequest.Resources
}
var file_api_v1_syncer_service_proto_depIdxs = []int32{
	6, // 0: llmariner.syncer.server.v1.PatchKubernetesObjectRequest.resources:type_name -> llmariner.syncer.server.v1.PatchKubernetesObjectRequest.Resources
	0, // 1: llmariner.syncer.server.v1.SyncerService.PatchKubernetesObject:input_type -> llmariner.syncer.server.v1.PatchKubernetesObjectRequest
	2, // 2: llmariner.syncer.server.v1.SyncerService.DeleteKubernetesObject:input_type -> llmariner.syncer.server.v1.DeleteKubernetesObjectRequest
	4, // 3: llmariner.syncer.server.v1.SyncerService.ListClusterIDs:input_type -> llmariner.syncer.server.v1.ListClusterIDsRequest
	1, // 4: llmariner.syncer.server.v1.SyncerService.PatchKubernetesObject:output_type -> llmariner.syncer.server.v1.PatchKubernetesObjectResponse
	3, // 5: llmariner.syncer.server.v1.SyncerService.DeleteKubernetesObject:output_type -> llmariner.syncer.server.v1.DeleteKubernetesObjectResponse
	5, // 6: llmariner.syncer.server.v1.SyncerService.ListClusterIDs:output_type -> llmariner.syncer.server.v1.ListClusterIDsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_syncer_service_proto_init() }
func file_api_v1_syncer_service_proto_init() {
	if File_api_v1_syncer_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_syncer_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchKubernetesObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_syncer_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchKubernetesObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_syncer_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKubernetesObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_syncer_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKubernetesObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_syncer_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_syncer_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListClusterIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_syncer_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchKubernetesObjectRequest_Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_syncer_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_syncer_service_proto_goTypes,
		DependencyIndexes: file_api_v1_syncer_service_proto_depIdxs,
		MessageInfos:      file_api_v1_syncer_service_proto_msgTypes,
	}.Build()
	File_api_v1_syncer_service_proto = out.File
	file_api_v1_syncer_service_proto_rawDesc = nil
	file_api_v1_syncer_service_proto_goTypes = nil
	file_api_v1_syncer_service_proto_depIdxs = nil
}
