apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "job-manager-syncer.fullname" . }}
  labels:
    {{- include "job-manager-syncer.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "job-manager-syncer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "job-manager-syncer.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
