kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  labels:
    ingress-ready: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 31234
    hostPort: 81
    protocol: TCP
  - containerPort: 31235
    hostPort: 82
    protocol: TCP
  - containerPort: 31236
    hostPort: 9000
    protocol: TCP
