global:
  worker:
    controlPlaneAddr: control-plane:8080
    registrationKeySecret:
      name: cluster-registration-key
      key: regKey

session-manager-agent:
  enable: true
  componentStatusSender:
    enable: false
  sessionManagerServerWorkerServiceAddr: control-plane:81

job-manager-dispatcher:
  enable: true
  logLevel: 4
  componentStatusSender:
    enable: false
  notebook:
    llmarinerBaseUrl: http://control-plane/v1
  version: latest
  image:
    repository: llmariner/job-manager-dispatcher
    pullPolicy: Never
