global:
  ingress:
    controllerUrl: http://localhost:8080
  workerServiceGrpcService:
    annotations:
      konghq.com/protocol: grpc
  workerServiceIngress:
    create: true
    ingressClassName: kong
    annotations:
      konghq.com/protocols: grpc,grpcs

session-manager-server:
  enable: true
  debugLog: true
  workerServiceHttpService:
    type: NodePort
    nodePort: 31234

dex-server:
  enable: true
rbac-server:
  enable: true
user-manager-server:
  enable: true
cluster-manager-server:
  enable: true
  defaultCluster: {}

job-manager-server:
  enable: true
  logLevel: 4
  syncerServiceGrpcService:
    annotations:
      konghq.com/protocol: grpc
  syncerServiceIngress:
    create: true
    annotations:
      konghq.com/protocols: grpc,grpcs
  version: latest
  image:
    repository: llmariner/job-manager-server
    pullPolicy: Never
