// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package legacy

import (
	context "context"
	v1 "github.com/llmariner/job-manager/api/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FineTuningWorkerServiceClient is the client API for FineTuningWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FineTuningWorkerServiceClient interface {
	ListQueuedInternalJobs(ctx context.Context, in *v1.ListQueuedInternalJobsRequest, opts ...grpc.CallOption) (*v1.ListQueuedInternalJobsResponse, error)
	GetInternalJob(ctx context.Context, in *v1.GetInternalJobRequest, opts ...grpc.CallOption) (*v1.InternalJob, error)
	// UpdateJobPhase updates the job status depending on the phase.
	UpdateJobPhase(ctx context.Context, in *v1.UpdateJobPhaseRequest, opts ...grpc.CallOption) (*v1.UpdateJobPhaseResponse, error)
}

type fineTuningWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFineTuningWorkerServiceClient(cc grpc.ClientConnInterface) FineTuningWorkerServiceClient {
	return &fineTuningWorkerServiceClient{cc}
}

func (c *fineTuningWorkerServiceClient) ListQueuedInternalJobs(ctx context.Context, in *v1.ListQueuedInternalJobsRequest, opts ...grpc.CallOption) (*v1.ListQueuedInternalJobsResponse, error) {
	out := new(v1.ListQueuedInternalJobsResponse)
	err := c.cc.Invoke(ctx, "/llmoperator.fine_tuning.server.v1.FineTuningWorkerService/ListQueuedInternalJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fineTuningWorkerServiceClient) GetInternalJob(ctx context.Context, in *v1.GetInternalJobRequest, opts ...grpc.CallOption) (*v1.InternalJob, error) {
	out := new(v1.InternalJob)
	err := c.cc.Invoke(ctx, "/llmoperator.fine_tuning.server.v1.FineTuningWorkerService/GetInternalJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fineTuningWorkerServiceClient) UpdateJobPhase(ctx context.Context, in *v1.UpdateJobPhaseRequest, opts ...grpc.CallOption) (*v1.UpdateJobPhaseResponse, error) {
	out := new(v1.UpdateJobPhaseResponse)
	err := c.cc.Invoke(ctx, "/llmoperator.fine_tuning.server.v1.FineTuningWorkerService/UpdateJobPhase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FineTuningWorkerServiceServer is the server API for FineTuningWorkerService service.
// All implementations must embed UnimplementedFineTuningWorkerServiceServer
// for forward compatibility
type FineTuningWorkerServiceServer interface {
	ListQueuedInternalJobs(context.Context, *v1.ListQueuedInternalJobsRequest) (*v1.ListQueuedInternalJobsResponse, error)
	GetInternalJob(context.Context, *v1.GetInternalJobRequest) (*v1.InternalJob, error)
	// UpdateJobPhase updates the job status depending on the phase.
	UpdateJobPhase(context.Context, *v1.UpdateJobPhaseRequest) (*v1.UpdateJobPhaseResponse, error)
	mustEmbedUnimplementedFineTuningWorkerServiceServer()
}

// UnimplementedFineTuningWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFineTuningWorkerServiceServer struct {
}

func (UnimplementedFineTuningWorkerServiceServer) ListQueuedInternalJobs(context.Context, *v1.ListQueuedInternalJobsRequest) (*v1.ListQueuedInternalJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueuedInternalJobs not implemented")
}
func (UnimplementedFineTuningWorkerServiceServer) GetInternalJob(context.Context, *v1.GetInternalJobRequest) (*v1.InternalJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInternalJob not implemented")
}
func (UnimplementedFineTuningWorkerServiceServer) UpdateJobPhase(context.Context, *v1.UpdateJobPhaseRequest) (*v1.UpdateJobPhaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobPhase not implemented")
}
func (UnimplementedFineTuningWorkerServiceServer) mustEmbedUnimplementedFineTuningWorkerServiceServer() {
}

// UnsafeFineTuningWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FineTuningWorkerServiceServer will
// result in compilation errors.
type UnsafeFineTuningWorkerServiceServer interface {
	mustEmbedUnimplementedFineTuningWorkerServiceServer()
}

func RegisterFineTuningWorkerServiceServer(s grpc.ServiceRegistrar, srv FineTuningWorkerServiceServer) {
	s.RegisterService(&FineTuningWorkerService_ServiceDesc, srv)
}

func _FineTuningWorkerService_ListQueuedInternalJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListQueuedInternalJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineTuningWorkerServiceServer).ListQueuedInternalJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmoperator.fine_tuning.server.v1.FineTuningWorkerService/ListQueuedInternalJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineTuningWorkerServiceServer).ListQueuedInternalJobs(ctx, req.(*v1.ListQueuedInternalJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FineTuningWorkerService_GetInternalJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetInternalJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineTuningWorkerServiceServer).GetInternalJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmoperator.fine_tuning.server.v1.FineTuningWorkerService/GetInternalJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineTuningWorkerServiceServer).GetInternalJob(ctx, req.(*v1.GetInternalJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FineTuningWorkerService_UpdateJobPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateJobPhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FineTuningWorkerServiceServer).UpdateJobPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmoperator.fine_tuning.server.v1.FineTuningWorkerService/UpdateJobPhase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FineTuningWorkerServiceServer).UpdateJobPhase(ctx, req.(*v1.UpdateJobPhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FineTuningWorkerService_ServiceDesc is the grpc.ServiceDesc for FineTuningWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FineTuningWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmoperator.fine_tuning.server.v1.FineTuningWorkerService",
	HandlerType: (*FineTuningWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListQueuedInternalJobs",
			Handler:    _FineTuningWorkerService_ListQueuedInternalJobs_Handler,
		},
		{
			MethodName: "GetInternalJob",
			Handler:    _FineTuningWorkerService_GetInternalJob_Handler,
		},
		{
			MethodName: "UpdateJobPhase",
			Handler:    _FineTuningWorkerService_UpdateJobPhase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/legacy/job_manager_service.proto",
}
